services:
  - type: web
    name: mental-health-twin-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: PIP_EXTRA_INDEX_URL
        value: https://download.pytorch.org/whl/cpu
      - key: PORT
        value: "5000"
  - type: postgresql
    name: mental-health-twin-db
    region: singapore
    plan: free
    ipAllowList: []
